# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ostatniego_przegladu', models.DateTimeField()),
                ('wycofany', models.BooleanField(default=False)),
                ('data_zakupu', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sztuki', models.IntegerField(default=0)),
                ('rezerwacja_od', models.DateTimeField()),
                ('rezerwacja_do', models.DateTimeField()),
                ('ilosc_godzin', models.IntegerField(default=0)),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Egzemplarz')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PunktSerwisowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sztuki', models.IntegerField(default=0)),
                ('rezerwacja_od', models.DateTimeField()),
                ('rezerwacja_do', models.DateTimeField()),
                ('ilosc_godzin', models.IntegerField(default=0)),
                ('zrealizowano', models.BooleanField(default=False)),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Egzemplarz')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Kategoria')),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Producent')),
            ],
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='punkt_serwisowy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.PunktSerwisowy'),
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='sprzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Sprzet'),
        ),
    ]
