# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='opis',
            field=models.CharField(default='opis', max_length=255),
            preserve_default=False,
        ),
    ]
