# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_sprzet_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='zdjecie_link',
            field=models.CharField(default='https://lh4.googleusercontent.com/Gjkpmy-tortfPiAnP3F4plzlLfeVDRr2Ngj0DGYWHGlGDXWMswY-bWLm15LBt2V03rJyEd6Q551abnA=w3840-h1804-rw', max_length=30),
            preserve_default=False,
        ),
    ]
