# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_sprzet_zdjecie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='zdjecie_link',
            field=models.CharField(max_length=255),
        ),
    ]
