# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_auto_20161121_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarz',
            name='wypozyczono',
            field=models.BooleanField(default=False),
        ),
    ]
