# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0005_egzemplarz_wypozyczono'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarz',
            name='wypozyczony_przez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
